import Workflow from "../models/Workflow.model.js";
import AIScenario from "../models/AIScenario.model.js";
import { v4 as uuidv4 } from "uuid";
import OpenAI from "openai";

// ⚙️ Setup your OpenAI client (or replace with Anthropic SDK if using Claude)
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

const formatLabel = (app) => {
  switch (app) {
    case "google_sheets":
      return "Google Sheets";
    case "email":
      return "Email";
    case "webhook":
      return "Webhook";
    default:
      return app.charAt(0).toUpperCase() + app.slice(1);
  }
};

/**
 * Generate a workflow from AI prompt
 */
export const generateAIWorkflow = async (req, res) => {
  try {
    const { prompt } = req.body;
    const userId = req.user._id;
    const organizationId = req.user.organizationId;

    if (!prompt) {
      return res.status(400).json({ message: "Prompt is required" });
    }

    // Save initial AI scenario (draft)
    const aiScenario = await AIScenario.create({
      userId,
      organizationId,
      name: `Workflow: ${prompt.slice(0, 50)}...`,
      prompt,
      model: "gpt-4o-mini",
      status: "processing",
    });

    // 🧠 Ask the AI to design a structured workflow
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        {
          role: "system",
          content: `You are an expert workflow automation generator like make.com or zapier.
Your job is to design automation workflows using ONLY the supported modules below.

SUPPORTED MODULES:
- webhook: Used as a trigger that starts the workflow when data is received via HTTP POST.
- google_sheets: Used to append data to a Google Sheet.
- email: Used to send an email notification.

⚠️ RULES:
1. Always respond ONLY in valid JSON (no text, comments, or markdown).
2. Use ONLY the supported modules above (no Slack, Discord, Notion, etc.).
3. All nodes must be custom nodes — do NOT use any "manual" or "manual trigger" types.
4. The workflow must start with a webhook trigger.
5. The workflow must include at least one action (e.g. Google Sheets or Email).
6. Keep the JSON strictly following this schema:

{
  "name": "string",
  "description": "string",
  "trigger": { "app": "webhook", "event": "on_receive" },
  "actions": [
    {
      "app": "google_sheets" | "email",
      "action": "append_row" | "send_email",
      "type": "google_sheets" | "email",
      "config": { "key": "value" }
    }
  ]
}

Return only the JSON that conforms to this schema.`,
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      temperature: 0.5,
    });
    // console.log(completion);
    // Parse AI output safely
    const rawText = completion.choices[0].message.content;
    let structured;
    try {
      structured = JSON.parse(rawText);
    } catch (err) {
      console.error("❌ JSON Parse Error:", rawText);
      throw new Error("Invalid AI response format");
    }

    // Create nodes and edges automatically for visualization
    const nodes = [
      {
        id: uuidv4(),
        type: "trigger",
        position: { x: 150, y: 100 },
        data: {
          label: formatLabel(structured.trigger.app),
          actionType: "webhook",
          config: structured.trigger,
        },
      },
      ...structured.actions.map((action, index) => ({
        id: uuidv4(),
        type: "action",
        position: { x: 400, y: 100 + index * 150 },
        data: {
          label: formatLabel(action.app),
          actionType: action.app,
          config: action.config,
        },
      })),
    ];

    const edges = nodes.slice(1).map((node, i) => ({
      id: uuidv4(),
      source: nodes[i].id,
      target: node.id,
      // label: "next",
    }));

    // Build workflow document
    const workflow = await Workflow.create({
      organizationId,
      userId,
      name: structured.name || "Untitled Workflow",
      description: structured.description || "Generated by AI",
      triggers: { type: "webhook", webhookSecret: uuidv4() },
      nodes,
      edges,
      actions: structured.actions.map((a, i) => ({
        nodeId: nodes[i + 1]?.id || uuidv4(),
        type: a.type || "custom",
        service: a.app,
        config: a.config || {},
      })),
      status: "draft",
    });

    // Update scenario
    aiScenario.response = rawText;
    aiScenario.status = "completed";
    await aiScenario.save();
    // console.log(workflow);
    res.status(200).json({
      success: true,
      workflow,
      message: "Workflow generated successfully!",
    });
  } catch (err) {
    console.error("❌ Error generating workflow:", err);
    res.status(500).json({
      message: err.message || "Failed to generate workflow",
    });
  }
};
